### ISSUE TITLE
is it possible to use external commands to update files

### ISSUE THREAD

**Issue by travi** [FormidableLabs/multibot#19]
after the revocation of tokens today, i thought this might be a helpful tool to update (well actually just append a new version of) encrypted `NPM_TOKEN` environment variables configured in `.travis.yml`.

while the input of the token would be the same for each repo, since the `travis` cli command encrypts differently for each repo, this doesn't seem like a good fit for a transform. 

my goal would be to run `travis encrypt NPM_TOKEN=<token here> --add env.global` for each repo. is this possible in a way that i'm overlooking?

**Comment by ryan-roemer** [comment]
`multibot` only uses the GitHub API and does nothing on the local filesystem / shell (that's one of the benefits -- not needing to git clone any repositories), so unfortunately, cannot run shell commands in each respository.

It's not specifically built for this, but if you have all the repositories that you want checked out, a single config file could allow you to exec a command in all the repos in parallel: https://github.com/FormidableLabs/lank

**Comment by travi** [comment]
ah, ok. that makes sense. 

not quite sure i have my head around how `lank` would work for this, but i'll investigate further as i continue thinking through this. i have a feeling that yesterday's attack and resulting token revocation wont be the last, so trying to consider options for rolling more easily.

thanks for the explanation and additional thoughts.
